#!/usr/bin/env python3
"""
Script dịch tiếng Việt cho Frappe framework.
Chạy bên trong container: python3 /tmp/translate_frappe.py
"""

import re
import os

PO_FILE = '/home/frappe/frappe-bench/apps/frappe/frappe/locale/vi.po'

# ============================================================
# TỪ ĐIỂN DỊCH — các chuỗi UI phổ biến nhất
# ============================================================
TRANSLATIONS = {
    # --- Buttons & Actions ---
    "Save": "Lưu",
    "Cancel": "Hủy",
    "Submit": "Gửi",
    "Delete": "Xóa",
    "Edit": "Chỉnh sửa",
    "Update": "Cập nhật",
    "Create": "Tạo mới",
    "Add": "Thêm",
    "Remove": "Xóa bỏ",
    "Close": "Đóng",
    "Search": "Tìm kiếm",
    "Filter": "Lọc",
    "Clear": "Xóa trắng",
    "Reset": "Đặt lại",
    "Refresh": "Làm mới",
    "Download": "Tải xuống",
    "Upload": "Tải lên",
    "Import": "Nhập",
    "Export": "Xuất",
    "Print": "In",
    "Preview": "Xem trước",
    "Copy": "Sao chép",
    "Paste": "Dán",
    "Duplicate": "Nhân bản",
    "Rename": "Đổi tên",
    "Merge": "Gộp",
    "Expand": "Mở rộng",
    "Collapse": "Thu gọn",
    "Next": "Tiếp theo",
    "Previous": "Quay lại",
    "Back": "Trở về",
    "Continue": "Tiếp tục",
    "Confirm": "Xác nhận",
    "Approve": "Phê duyệt",
    "Reject": "Từ chối",
    "Discard": "Hủy bỏ",
    "Amend": "Sửa đổi",
    "Assign": "Phân công",
    "Share": "Chia sẻ",
    "Tag": "Gắn thẻ",
    "Like": "Thích",
    "Follow": "Theo dõi",
    "Unfollow": "Bỏ theo dõi",
    "Attach": "Đính kèm",
    "Detach": "Gỡ đính kèm",
    "Link": "Liên kết",
    "Unlink": "Gỡ liên kết",
    "Enable": "Bật",
    "Disable": "Tắt",
    "Activate": "Kích hoạt",
    "Deactivate": "Vô hiệu hóa",
    "Archive": "Lưu trữ",
    "Restore": "Khôi phục",
    "Reload": "Tải lại",
    "Run": "Chạy",
    "Execute": "Thực thi",
    "Apply": "Áp dụng",
    "Set": "Đặt",
    "Get": "Lấy",
    "Select": "Chọn",
    "Deselect": "Bỏ chọn",
    "Check": "Kiểm tra",
    "Uncheck": "Bỏ chọn",
    "Mark": "Đánh dấu",
    "Flag": "Gắn cờ",
    "Pin": "Ghim",
    "Unpin": "Bỏ ghim",
    "Star": "Đánh dấu sao",
    "Unstar": "Bỏ đánh dấu sao",
    "View": "Xem",
    "Hide": "Ẩn",
    "Show": "Hiện",
    "Open": "Mở",
    "New": "Mới",
    "Add Row": "Thêm dòng",
    "Delete Row": "Xóa dòng",
    "Insert Row": "Chèn dòng",
    "Move Up": "Di chuyển lên",
    "Move Down": "Di chuyển xuống",
    "Scroll to top": "Cuộn lên đầu",

    # --- Navigation ---
    "Home": "Trang chủ",
    "Dashboard": "Bảng điều khiển",
    "Settings": "Cài đặt",
    "Profile": "Hồ sơ",
    "Logout": "Đăng xuất",
    "Login": "Đăng nhập",
    "Sign In": "Đăng nhập",
    "Sign Out": "Đăng xuất",
    "Sign Up": "Đăng ký",
    "Register": "Đăng ký",
    "Forgot Password": "Quên mật khẩu",
    "Reset Password": "Đặt lại mật khẩu",
    "Change Password": "Đổi mật khẩu",
    "My Profile": "Hồ sơ của tôi",
    "My Account": "Tài khoản của tôi",
    "My Settings": "Cài đặt của tôi",
    "Notifications": "Thông báo",
    "Help": "Trợ giúp",
    "About": "Giới thiệu",
    "Documentation": "Tài liệu",
    "Shortcuts": "Phím tắt",
    "Modules": "Phân hệ",
    "Apps": "Ứng dụng",
    "Workspaces": "Không gian làm việc",
    "Favorites": "Yêu thích",
    "Recent": "Gần đây",
    "Starred": "Đã đánh dấu sao",
    "Assigned": "Được phân công",
    "Mentions": "Đề cập",
    "Activity": "Hoạt động",
    "Timeline": "Dòng thời gian",
    "Inbox": "Hộp thư đến",
    "Outbox": "Hộp thư đi",
    "Drafts": "Bản nháp",
    "Trash": "Thùng rác",
    "Bookmarks": "Dấu trang",
    "Report": "Báo cáo",
    "Reports": "Báo cáo",
    "List": "Danh sách",
    "Tree": "Dạng cây",
    "Kanban": "Kanban",
    "Calendar": "Lịch",
    "Gantt": "Biểu đồ Gantt",
    "Map": "Bản đồ",
    "Image": "Hình ảnh",
    "Form": "Biểu mẫu",

    # --- Common Fields ---
    "Name": "Tên",
    "Title": "Tiêu đề",
    "Description": "Mô tả",
    "Date": "Ngày",
    "Time": "Giờ",
    "From Date": "Từ ngày",
    "To Date": "Đến ngày",
    "Start Date": "Ngày bắt đầu",
    "End Date": "Ngày kết thúc",
    "Due Date": "Hạn chót",
    "Created On": "Ngày tạo",
    "Modified On": "Ngày sửa",
    "Created By": "Tạo bởi",
    "Modified By": "Sửa bởi",
    "Owner": "Chủ sở hữu",
    "Assigned To": "Giao cho",
    "Status": "Trạng thái",
    "Type": "Loại",
    "Category": "Danh mục",
    "Group": "Nhóm",
    "Priority": "Độ ưu tiên",
    "Company": "Công ty",
    "Currency": "Tiền tệ",
    "Amount": "Số tiền",
    "Quantity": "Số lượng",
    "Rate": "Giá",
    "Total": "Tổng cộng",
    "Subtotal": "Tổng phụ",
    "Tax": "Thuế",
    "Discount": "Chiết khấu",
    "Remarks": "Ghi chú",
    "Notes": "Ghi chú",
    "Comment": "Bình luận",
    "Comments": "Bình luận",
    "Attachments": "Tệp đính kèm",
    "Tags": "Thẻ",
    "Reference": "Tham chiếu",
    "ID": "Mã",
    "Code": "Mã",
    "Series": "Số seri",
    "No": "Không",
    "Yes": "Có",
    "Active": "Hoạt động",
    "Inactive": "Không hoạt động",
    "Enabled": "Đã bật",
    "Disabled": "Đã tắt",
    "Draft": "Bản nháp",
    "Submitted": "Đã gửi",
    "Cancelled": "Đã hủy",
    "Pending": "Đang chờ",
    "Open": "Mở",
    "Closed": "Đã đóng",
    "Completed": "Hoàn thành",
    "In Progress": "Đang thực hiện",
    "Overdue": "Quá hạn",
    "Resolved": "Đã giải quyết",
    "Expired": "Đã hết hạn",
    "Mandatory": "Bắt buộc",
    "Optional": "Tùy chọn",
    "Required": "Bắt buộc",
    "Unique": "Duy nhất",
    "Read Only": "Chỉ đọc",
    "Hidden": "Ẩn",
    "Depends On": "Phụ thuộc vào",
    "Default": "Mặc định",
    "Label": "Nhãn",
    "Value": "Giá trị",
    "Options": "Tùy chọn",
    "Fieldname": "Tên trường",
    "Fieldtype": "Loại trường",
    "Data": "Dữ liệu",
    "Text": "Văn bản",
    "Number": "Số",
    "Float": "Số thực",
    "Integer": "Số nguyên",
    "Percentage": "Phần trăm",
    "Currency": "Tiền tệ",
    "Select": "Lựa chọn",
    "Link": "Liên kết",
    "Table": "Bảng",
    "Check": "Kiểm tra",
    "Date": "Ngày",
    "Datetime": "Ngày giờ",
    "Color": "Màu sắc",
    "Rating": "Đánh giá",
    "Signature": "Chữ ký",
    "HTML": "HTML",
    "Markdown": "Markdown",
    "Attach": "Đính kèm",
    "Attach Image": "Đính kèm hình ảnh",
    "Geolocation": "Vị trí địa lý",
    "Phone": "Điện thoại",
    "Email": "Email",
    "Website": "Trang web",
    "Password": "Mật khẩu",
    "Barcode": "Mã vạch",

    # --- Messages ---
    "Success": "Thành công",
    "Error": "Lỗi",
    "Warning": "Cảnh báo",
    "Info": "Thông tin",
    "Loading": "Đang tải",
    "Saving": "Đang lưu",
    "Updating": "Đang cập nhật",
    "Deleting": "Đang xóa",
    "Processing": "Đang xử lý",
    "Please wait": "Vui lòng chờ",
    "Done": "Xong",
    "Failed": "Thất bại",
    "Not Found": "Không tìm thấy",
    "Access Denied": "Truy cập bị từ chối",
    "Permission Denied": "Không có quyền",
    "Not Permitted": "Không được phép",
    "Unauthorized": "Chưa xác thực",
    "Session Expired": "Phiên đã hết hạn",
    "No records found": "Không có bản ghi",
    "No data": "Không có dữ liệu",
    "No results": "Không có kết quả",
    "No items": "Không có mục nào",
    "Empty": "Trống",
    "None": "Không có",
    "All": "Tất cả",
    "Others": "Khác",
    "Unknown": "Không xác định",
    "Unlimited": "Không giới hạn",
    "N/A": "Không áp dụng",
    "Invalid": "Không hợp lệ",
    "Valid": "Hợp lệ",
    "Verified": "Đã xác minh",
    "Unverified": "Chưa xác minh",
    "Saved": "Đã lưu",
    "Submitted": "Đã gửi",
    "Cancelled": "Đã hủy",
    "Amended": "Đã sửa đổi",

    # --- Dialogs & Prompts ---
    "Are you sure?": "Bạn có chắc không?",
    "Yes": "Có",
    "No": "Không",
    "OK": "Đồng ý",
    "Okay": "Đồng ý",
    "Proceed": "Tiến hành",
    "Continue": "Tiếp tục",
    "Cancel": "Hủy",
    "Close": "Đóng",
    "Submit": "Gửi",
    "Confirm": "Xác nhận",
    "This action cannot be undone": "Hành động này không thể hoàn tác",
    "Are you sure you want to delete": "Bạn có chắc muốn xóa",
    "This is a mandatory field": "Đây là trường bắt buộc",

    # --- Permissions ---
    "Permissions": "Quyền hạn",
    "Role": "Vai trò",
    "Roles": "Vai trò",
    "User": "Người dùng",
    "Users": "Người dùng",
    "Guest": "Khách",
    "Administrator": "Quản trị viên",
    "Manager": "Quản lý",
    "Read": "Đọc",
    "Write": "Ghi",
    "Create": "Tạo",
    "Delete": "Xóa",
    "Submit": "Gửi",
    "Cancel": "Hủy",
    "Amend": "Sửa đổi",
    "Report": "Báo cáo",
    "Import": "Nhập",
    "Export": "Xuất",
    "Print": "In",
    "Email": "Email",
    "Share": "Chia sẻ",
    "If Owner": "Nếu là chủ sở hữu",

    # --- Time & Date ---
    "Today": "Hôm nay",
    "Yesterday": "Hôm qua",
    "Tomorrow": "Ngày mai",
    "This Week": "Tuần này",
    "Last Week": "Tuần trước",
    "This Month": "Tháng này",
    "Last Month": "Tháng trước",
    "This Quarter": "Quý này",
    "This Year": "Năm nay",
    "Last Year": "Năm ngoái",
    "Custom": "Tùy chỉnh",
    "Monday": "Thứ Hai",
    "Tuesday": "Thứ Ba",
    "Wednesday": "Thứ Tư",
    "Thursday": "Thứ Năm",
    "Friday": "Thứ Sáu",
    "Saturday": "Thứ Bảy",
    "Sunday": "Chủ Nhật",
    "January": "Tháng Một",
    "February": "Tháng Hai",
    "March": "Tháng Ba",
    "April": "Tháng Tư",
    "May": "Tháng Năm",
    "June": "Tháng Sáu",
    "July": "Tháng Bảy",
    "August": "Tháng Tám",
    "September": "Tháng Chín",
    "October": "Tháng Mười",
    "November": "Tháng Mười Một",
    "December": "Tháng Mười Hai",
    "AM": "SA",
    "PM": "CH",
    "seconds": "giây",
    "minutes": "phút",
    "hours": "giờ",
    "days": "ngày",
    "weeks": "tuần",
    "months": "tháng",
    "years": "năm",
    "ago": "trước",
    "from now": "từ bây giờ",

    # --- DocType system ---
    "DocType": "Loại tài liệu",
    "Document": "Tài liệu",
    "Documents": "Tài liệu",
    "Record": "Bản ghi",
    "Records": "Bản ghi",
    "Field": "Trường",
    "Fields": "Trường",
    "Row": "Dòng",
    "Rows": "Dòng",
    "Column": "Cột",
    "Columns": "Cột",
    "Table": "Bảng",
    "Tab": "Tab",
    "Section": "Phần",
    "Column Break": "Ngắt cột",
    "Section Break": "Ngắt phần",
    "Page Break": "Ngắt trang",
    "Heading": "Tiêu đề",
    "Subheading": "Tiêu đề phụ",
    "HTML": "HTML",
    "Workflow": "Quy trình",
    "Workflow State": "Trạng thái quy trình",
    "Workflow Action": "Hành động quy trình",
    "Print Format": "Định dạng in",
    "Email Template": "Mẫu email",
    "Custom Field": "Trường tùy chỉnh",
    "Custom Script": "Script tùy chỉnh",
    "Server Script": "Script máy chủ",
    "Client Script": "Script máy khách",
    "Translation": "Bản dịch",

    # --- Pagination & Lists ---
    "Page": "Trang",
    "of": "trong",
    "rows": "dòng",
    "per page": "mỗi trang",
    "First": "Đầu tiên",
    "Last": "Cuối cùng",
    "Sort By": "Sắp xếp theo",
    "Group By": "Nhóm theo",
    "Ascending": "Tăng dần",
    "Descending": "Giảm dần",
    "Total": "Tổng",
    "Count": "Số lượng",
    "Sum": "Tổng",
    "Average": "Trung bình",
    "Min": "Nhỏ nhất",
    "Max": "Lớn nhất",
    "Show": "Hiện",
    "Hide": "Ẩn",
    "Columns": "Cột",
    "Filters": "Bộ lọc",
    "Add Filter": "Thêm bộ lọc",
    "Remove Filter": "Xóa bộ lọc",
    "Clear Filters": "Xóa tất cả bộ lọc",

    # --- Email & Communication ---
    "Email": "Email",
    "To": "Đến",
    "CC": "CC",
    "BCC": "BCC",
    "Subject": "Tiêu đề",
    "Message": "Nội dung",
    "Sender": "Người gửi",
    "Recipient": "Người nhận",
    "Reply": "Trả lời",
    "Reply All": "Trả lời tất cả",
    "Forward": "Chuyển tiếp",
    "Send": "Gửi",
    "Sent": "Đã gửi",
    "Received": "Đã nhận",
    "Unread": "Chưa đọc",
    "Read": "Đã đọc",
    "Starred": "Đã đánh dấu sao",
    "Important": "Quan trọng",
    "Spam": "Thư rác",

    # --- Address & Contact ---
    "Address": "Địa chỉ",
    "City": "Thành phố",
    "State": "Tỉnh/Thành phố",
    "Country": "Quốc gia",
    "Zip Code": "Mã bưu điện",
    "Phone": "Điện thoại",
    "Mobile": "Di động",
    "Fax": "Fax",
    "Website": "Trang web",
    "Contact": "Liên hệ",
    "Contacts": "Liên hệ",
    "Customer": "Khách hàng",
    "Supplier": "Nhà cung cấp",
    "Employee": "Nhân viên",
    "First Name": "Tên",
    "Last Name": "Họ",
    "Full Name": "Họ và tên",
    "Gender": "Giới tính",
    "Male": "Nam",
    "Female": "Nữ",
    "Other": "Khác",
    "Date of Birth": "Ngày sinh",
    "Designation": "Chức danh",
    "Department": "Phòng ban",

    # --- System ---
    "System": "Hệ thống",
    "System Settings": "Cài đặt hệ thống",
    "Global Settings": "Cài đặt toàn cục",
    "General Settings": "Cài đặt chung",
    "Backup": "Sao lưu",
    "Restore": "Khôi phục",
    "Install": "Cài đặt",
    "Uninstall": "Gỡ cài đặt",
    "Update": "Cập nhật",
    "Upgrade": "Nâng cấp",
    "Version": "Phiên bản",
    "License": "Giấy phép",
    "Support": "Hỗ trợ",
    "Feedback": "Phản hồi",
    "Bug Report": "Báo lỗi",
    "Feature Request": "Yêu cầu tính năng",
    "Language": "Ngôn ngữ",
    "Timezone": "Múi giờ",
    "Theme": "Giao diện",
    "Font": "Phông chữ",
    "Logo": "Logo",
    "Favicon": "Favicon",
    "Cache": "Bộ nhớ đệm",
    "Clear Cache": "Xóa bộ nhớ đệm",
    "Logs": "Nhật ký",
    "Error Log": "Nhật ký lỗi",
    "Activity Log": "Nhật ký hoạt động",
    "Audit Log": "Nhật ký kiểm toán",
    "Scheduled Jobs": "Công việc định kỳ",
    "Background Jobs": "Công việc nền",

    # --- Miscellaneous ---
    "Details": "Chi tiết",
    "More Details": "Thêm chi tiết",
    "Summary": "Tóm tắt",
    "Overview": "Tổng quan",
    "Information": "Thông tin",
    "Configuration": "Cấu hình",
    "Template": "Mẫu",
    "Preview": "Xem trước",
    "History": "Lịch sử",
    "Revision": "Phiên bản",
    "Version": "Phiên bản",
    "Change Log": "Nhật ký thay đổi",
    "Audit Trail": "Dấu vết kiểm toán",
    "Annotation": "Chú thích",
    "Review": "Xem xét",
    "Approve": "Phê duyệt",
    "Reject": "Từ chối",
    "Escalate": "Leo thang",
    "Archive": "Lưu trữ",
    "Clone": "Nhân bản",
    "Duplicate": "Sao chép",
    "Bulk Actions": "Hành động hàng loạt",
    "Mass Update": "Cập nhật hàng loạt",
    "Import Data": "Nhập dữ liệu",
    "Export Data": "Xuất dữ liệu",
    "Download Template": "Tải mẫu",
    "Upload File": "Tải tệp lên",
    "Drag and drop": "Kéo và thả",
    "Browse": "Duyệt",
    "File": "Tệp",
    "Files": "Tệp",
    "Folder": "Thư mục",
    "Image": "Hình ảnh",
    "Video": "Video",
    "Audio": "Âm thanh",
    "PDF": "PDF",
    "Spreadsheet": "Bảng tính",
    "Document": "Tài liệu",
    "Max file size": "Kích thước tệp tối đa",
    "File size exceeded": "Kích thước tệp vượt quá giới hạn",
    "Invalid file type": "Loại tệp không hợp lệ",
    "Permission": "Quyền",
    "Permissions": "Quyền hạn",
    "Access": "Truy cập",
    "Restrict": "Hạn chế",
    "Allow": "Cho phép",
    "Deny": "Từ chối",
    "Block": "Chặn",
    "Whitelist": "Danh sách trắng",
    "Blacklist": "Danh sách đen",
    "API": "API",
    "Webhook": "Webhook",
    "Integration": "Tích hợp",
    "Sync": "Đồng bộ",
    "Queue": "Hàng đợi",
    "Retry": "Thử lại",
    "Skip": "Bỏ qua",
    "Ignore": "Bỏ qua",
    "Override": "Ghi đè",
    "Merge": "Gộp",
    "Split": "Tách",
    "Convert": "Chuyển đổi",
    "Generate": "Tạo",
    "Calculate": "Tính toán",
    "Validate": "Kiểm tra hợp lệ",
    "Verify": "Xác minh",
    "Authenticate": "Xác thực",
    "Authorize": "Ủy quyền",
    "Encrypt": "Mã hóa",
    "Decrypt": "Giải mã",

    # --- ERPNext specific common strings ---
    "Item": "Sản phẩm",
    "Items": "Sản phẩm",
    "Stock": "Tồn kho",
    "Warehouse": "Kho hàng",
    "Invoice": "Hóa đơn",
    "Order": "Đơn hàng",
    "Purchase": "Mua hàng",
    "Sales": "Bán hàng",
    "Payment": "Thanh toán",
    "Account": "Tài khoản",
    "Accounts": "Kế toán",
    "Ledger": "Sổ cái",
    "Journal": "Nhật ký",
    "Payable": "Phải trả",
    "Receivable": "Phải thu",
    "Balance": "Số dư",
    "Debit": "Nợ",
    "Credit": "Có",
    "Profit": "Lợi nhuận",
    "Loss": "Lỗ",
    "Asset": "Tài sản",
    "Liability": "Nợ phải trả",
    "Equity": "Vốn chủ sở hữu",
    "Revenue": "Doanh thu",
    "Expense": "Chi phí",
    "Budget": "Ngân sách",
    "Project": "Dự án",
    "Task": "Nhiệm vụ",
    "Issue": "Vấn đề",
    "Ticket": "Phiếu",
    "Lead": "Tiềm năng",
    "Opportunity": "Cơ hội",
    "Quotation": "Báo giá",
    "Contract": "Hợp đồng",
    "Territory": "Khu vực",
    "Branch": "Chi nhánh",
    "Cost Center": "Trung tâm chi phí",
    "Fiscal Year": "Năm tài chính",
    "Accounting Period": "Kỳ kế toán",
}


def translate_po_file(po_path, translations):
    with open(po_path, 'r', encoding='utf-8') as f:
        content = f.read()

    count = 0
    for source, target in translations.items():
        # Escape special characters for exact match in PO format
        escaped_source = source.replace('"', '\\"')
        escaped_target = target.replace('"', '\\"')

        old = f'msgid "{escaped_source}"\nmsgstr ""'
        new = f'msgid "{escaped_source}"\nmsgstr "{escaped_target}"'

        if old in content:
            content = content.replace(old, new)
            count += 1

    with open(po_path, 'w', encoding='utf-8') as f:
        f.write(content)

    return count


if __name__ == '__main__':
    print(f"Processing {PO_FILE}...")
    count = translate_po_file(PO_FILE, TRANSLATIONS)
    print(f"Translated {count} strings successfully.")
    print(f"Total translations in dictionary: {len(TRANSLATIONS)}")
